Require pyparsing<2.0.0 in requirements.txt
pyparsing 2.0.0 only supports Python 3.x, and trying to install it on
Python 2.x fails with an error:

  Traceback (most recent call last):
    [...]
    File "pyparsing.py", line 629
      nonlocal limit,foundArity
                   ^
  SyntaxError: invalid syntax

See http://sourceforge.net/projects/pyparsing/forums/forum/337293/topic/6481050