LDAP broken since Graphite 1.0
LDAP_BASE_USER/LDAP_BASE_PASS setting has been broken since
the LDAP_USER_DN_TEMPLATE setting was introduced in commit
871a6cb427cbb1d8a1c33905d6f25e4b39d8a5b7.

By not giving LDAP_USER_DN_TEMPLATE a default value in
settings.py, the expected attribute could not be fetched in
ldapBackend.py and logins fails with:

AttributeError: 'Settings' object has no attribute
	'LDAP_USER_DN_TEMPLATE'

Change-Id: Ib1bf9421d041cb7d7418579d264c5618dc3e9485