avoid ZeroDivisionError when graphing only one constantLine() target
without this patch, when graphing a constantLine without other targets
with actual data, the rendering fails with such a stack trace:

Traceback (most recent call last):
  File ".../deps/django/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File ".../webapp/graphite/render/views.py", line 200, in renderView
    image = doImageRender(requestOptions['graphClass'], graphOptions)
  File ".../webapp/graphite/render/views.py", line 408, in doImageRender
    img = graphClass(**graphOptions)
  File ".../webapp/graphite/render/glyph.py", line 195, in __init__
    self.drawGraph(**params)
  File ".../webapp/graphite/render/glyph.py", line 667, in drawGraph
    self.consolidateDataPoints()
  File ".../webapp/graphite/render/glyph.py", line 1010, in consolidateDataPoints
    bestXStep = numberOfPixels / divisor
ZeroDivisionError: float division

Conflicts:
	webapp/graphite/render/functions.py