get whisper from github
Problem is that the 0.9.x branch is not compatible with the whisper we get from
PyPi, which is 0.9.12. This has the following effect:

return whisper.fetch(self.fs_path, startTime, endTime, now)
TypeError: fetch() takes at most 3 arguments (4 given)

Getting the whisper from github master fixes this.